### ISSUE TITLE
Can not add group widget

### ISSUE THREAD

**Issue by poVoq** [ColdTrick/best_practices#3] opened 2014-03-26 12:59 UTC
When trying to add an best practise group widget the following elgg error is shown:
"We could not add your widget."

**Comment by jdalsem** [comment] 2014-04-07 07:03
is your default acces by any change private?

**Comment by poVoq** [comment] 2014-04-07 07:31
No, all default elgg settings, i.e. public access by default.

**Comment by jdalsem** [comment] 2014-04-07 10:57
which version of widget manager are you using?

**Comment by poVoq** [comment] 2014-04-07 11:37
latest 4.8

**Comment by poVoq** [comment] 2014-04-07 11:49
Another strange thing is that I can't manage that widget in the administrator interface like the other widgets (I can not for example hide it). It just doesn't show up in the admin interface at all.

**Comment by jdalsem** [comment] 2015-01-27 15:38
Closing as being unable to reproduce

**Closed as completed by jdalsem** 2015-01-27 15:38 UTC
